name: Executar ShortIA Vertex AI

on: [push]

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Configurar Credenciais do Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json" >> $GITHUB_ENV

      - name: Executar o script principal
        run: python main.py
